---
layout: post
title: ! 'Propel needs a new leader: Do you want to take the responsibility for the
  future of an awesome ORM?'
published: true
---
<p>For the past two years, I've been the Propel Project lead. It's been an incredibly pleasant experience. Being involved in an open-source project brings a lot of feedback and motivation, but leading one is even better. You get to draw the architecture, meet great people, guide contributors to match your ideas, communicate and make other contributors communicate with each other, give conferences, trainings, advice, etc. And the Propel ORM is not your neighbor's pet project. It's been created six years ago, it's now used in tens of thousand of websites across the world, it covers a wide range of uses, it brings innovative solutions, and it follows professional development methods. Well, if you read this blog, you know what I'm talking about. So leading this particular project brought even more exposure, contributions, expectations, and pressure than with a standard open-source project.</p>
<p>But now, after two years, it's time to step down. Having me as project leader is what prevents Propel from developing even faster, and for a simple reason: I don't have enough time to dedicate to it. I can't qualify all the tickets, answer the proposals for conferences, design the next great features, with only a few hours a week. And to be completely honest, I took over the project two years ago because I didn't want to see it die, not because I wanted to lead an open-source project. But today Propel is not dying anymore, and I want to say "mission accomplished". And I would like to give the beautiful baby to someone that will know better than me how to make it grow even further.</p>
<p>So this is an incredible opportunity for a developer wanting to test - or confirm - his/her abilities at leading an open-source project.&nbsp;</p>
<p>Do you need to know the Propel source code by heart? Of course not. When I took over Propel, I had only a vague understanding of all the cogs that make Propel work. And even today, some of them are still somehow mysterious to me (can someone please explain me how validation works?). That's a big library, but that's also a big community, so there are many people willing to help you fix bugs for a particular platform, a particular use case, or to address a new feature.&nbsp;</p>
<p>Do you need to be a Propel contributor already? Not necessarily. If you can provide examples of your coding style so that I can make sure I'm not passing the jewel to a smuggler, I'm fine with it. Of course, you should favor test-driven development, have a few real-world projects using Propel to test your ideas, and read a lot of code from other libraries to avoid reinventing the wheel.</p>
<p>Do you need to be passionate about Propel? At least a little. This is not something you get paid for. This is not something your girlfriend will encourage you to do. The motivation you need to lead this project has to see with the will to ease the life of your fellow developers, and to build up a kick-ass ActiveRecord implementation in PHP.</p>
<p>If you think you fit the costume, send me an email - you should know my address if you're a subscriber of any of the Propel mailing-lists. As for me, I will continue to fix bugs on the 1.6 branch. My team use Propel on an everyday basis, so they will go on contributing as well. But expect no new feature to come from me.&nbsp;</p>
<p>I'm retiring from Propel: make way for the young!</p>
<p>&nbsp;</p>
