---
layout: post
title: We’re Hiring PHP5 Developers
published: true
---
<p><span style="">In addition to being the Propel lead developer, I&rsquo;m the CTO of e-TF1, and proud of the work of my development team. They are fast, they are efficient, and they deliver on time.</span></p>
<p><span style="">At e-TF1, we develop and maintain the French leading Media website, <a href="http://www.tf1.fr/">TF1.fr</a> (in 2010, TF1 was the 7<sup>th</sup> group in the French web, and the first Media group according to Nielsen NetRatings). We also edit a lot of other web properties (<a href="http://www.tf1vision.com/">TF1Vision.com</a>, <a href="http://www.plurielles.fr/">Plurielles.fr</a>, <a href="http://www.excessif.com/">Excessif.com</a>, <a href="http://www.psg.fr">PSG.fr</a>, <a href="http://www.om.net">OM.net</a>, etc.). We don&rsquo;t just do web, though; e-TF1 also develops IPTV services (like <a href="http://www.01net.com/editorial/530254/la-television-de-rattrapage-de-tf1-disponible-sur-la-freebox/">MyTF1</a>, just released for the French ISP Free in addition to Orange and Bouygues Telecom), Mobile apps (the <a href="http://itunes.apple.com/fr/app/tf1/id407248490">TF1.fr</a> iPhone/iPad app, developed in-house, has been in the French top 25 apps since it&rsquo;s been released), and ConnectTV apps.</span></p>
<p><span style="">Our job is to keep up with the constant evolution of the Media world. News TV shows, new ideas, new web opportunities, new video formats, skyrocketing traffic, TV and mobile devices changing every other month: that&rsquo;s our day-to-day work. We always have to deliver on time with short notice &ndash; without sacrificing on the quality. Most our projects last a couple months at maximum, in small teams, and must support millions of users from day one. &ldquo;Agile&rdquo; flows in our veins, &ldquo;teamwork&rdquo; is written in our genes, and quality is not negotiable. We&rsquo;re passionate. </span></p>
<p><span style="">All that work relies on technology. As you might expect, we&rsquo;re strong fans of Open Source Software &ndash; <a href="http://www.propelorm.org">Propel </a>is our contribution back to the community for all the goodness we got from PHP, Symfony, Zend Framework, PHPUnit, PEAR, Apache, MySQL, MongoDB, NodeJS, Capistrano, Redmine, Jenkins, and the likes. We encourage innovation, and we emphasize on the fun. Our developers are not writing code: they&rsquo;re building products. </span></p>
<p><span style="">Today, we&rsquo;re looking to expand our internal development team. We are not looking for magicians. We are not looking for contractors. We are looking for technology enthusiasts, with at least a couple years of experience in PHP5, and a strong taste for good code. Autonomous and innovative, you&rsquo;re aware of the state-of-the art coding techniques. Our team speaks French and English, and is located in Boulogne-Billancourt, close to Paris, France &ndash; that&rsquo;s where the position is, we need proximity to be reactive enough. The salary is good &ndash; as good as you are.</span></p>
<p><span style="">If you are looking for the best place to work in France as a PHP developer, stop by and <a href="http://tf1.profils.org/offre-de-emploi/emploi-developpeur-se-h-f_3374.aspx">send us your CV</a>. You won&rsquo;t be disappointed.</span></p>
<p>&nbsp;</p>
